# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d0a4b27d9225c658f3845f5129bfe6674b23d22e758602d6098133924b15d85ac96b65495ae803f4f4b7542be479fc0ac313a11a7f0c9edcc96af029ddfa250

test:
  secret_key_base: a00b9d56d2f2e27bb96659841f8c104f23c3031c99d3b8cba7bc96ca58daf2548cbdfe731dfd433c885f9811b15b3da7e78f4ca7e25929cea159c80f2adc5915

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
